// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy9SCLX411BhLFgFAxRvtRlO9V-kw_ozw',
    appId: '1:734351928285:web:c1843f2a88d1d8c3642434',
    messagingSenderId: '734351928285',
    projectId: 'fomis-gofa-college',
    authDomain: 'fomis-gofa-college.firebaseapp.com',
    storageBucket: 'fomis-gofa-college.firebasestorage.app',
    measurementId: 'G-V5NZ47BJ9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC84jY-oSskmYplGdWcoNo-PNulQGwzGIc',
    appId: '1:734351928285:android:d425e57fa6470cac642434',
    messagingSenderId: '734351928285',
    projectId: 'fomis-gofa-college',
    storageBucket: 'fomis-gofa-college.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYgoGM8Ty0cKGT_aJYBnUceZ8t5PC_vQ',
    appId: '1:734351928285:ios:63a90d34a75fbb4e642434',
    messagingSenderId: '734351928285',
    projectId: 'fomis-gofa-college',
    storageBucket: 'fomis-gofa-college.firebasestorage.app',
    iosBundleId: 'com.example.fomisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwYgoGM8Ty0cKGT_aJYBnUceZ8t5PC_vQ',
    appId: '1:734351928285:ios:63a90d34a75fbb4e642434',
    messagingSenderId: '734351928285',
    projectId: 'fomis-gofa-college',
    storageBucket: 'fomis-gofa-college.firebasestorage.app',
    iosBundleId: 'com.example.fomisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy9SCLX411BhLFgFAxRvtRlO9V-kw_ozw',
    appId: '1:734351928285:web:b9084c197eaa377d642434',
    messagingSenderId: '734351928285',
    projectId: 'fomis-gofa-college',
    authDomain: 'fomis-gofa-college.firebaseapp.com',
    storageBucket: 'fomis-gofa-college.firebasestorage.app',
    measurementId: 'G-S53JN8DGH0',
  );
}
