import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// PDF generation + print-preview helpers for the GIC EFOMIS portal.
///
/// Every document uses the same professional, institutional layout:
///   1. Header — "Gofa Industrial College - Enterprise Visit Report"
///   2. Document details — date, department, expert, enterprise, contact info
///   3. Form sections — objectives, dynamic template fields, findings,
///      recommendations, approval status
///   4. Sign-off block — reviewer notes + signature spaces for the
///      Department Head and Dean
///
/// `printing` renders a native print preview (desktop/web/mobile) so the
/// college can keep physical archive copies.

// ---------------------------------------------------------------------------
// Small formatting helpers
// ---------------------------------------------------------------------------

String _str(dynamic v) => (v ?? '').toString().trim();

String _orDash(dynamic v) {
  final s = _str(v);
  return s.isEmpty ? '—' : s;
}

String _fmtDate(dynamic raw) {
  if (raw is Timestamp) {
    final dt = raw.toDate();
    return '${dt.day.toString().padLeft(2, '0')}/'
        '${dt.month.toString().padLeft(2, '0')}/${dt.year}';
  }
  final s = _str(raw);
  return s.isEmpty ? '—' : s;
}

// Split a tasks/objectives string into bullets (newline first, then commas).
List<String> _lines(String? raw) {
  if (raw == null || raw.trim().isEmpty) return const [];
  final lines =
      raw.split('\n').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
  if (lines.length > 1) return lines;
  return raw.split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
}

// ---------------------------------------------------------------------------
// Shared layout building blocks
// ---------------------------------------------------------------------------

pw.Widget _header(String subtitle) {
  return pw.Container(
    padding: const pw.EdgeInsets.only(bottom: 10),
    decoration: pw.BoxDecoration(
      border: pw.Border(bottom: pw.BorderSide(color: PdfColors.indigo800, width: 1.4)),
    ),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Gofa Industrial College',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
        pw.Text('Enterprise Visit Report',
            style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo700)),
        pw.SizedBox(height: 3),
        pw.Text(subtitle, style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
      ],
    ),
  );
}

pw.Widget _footer(pw.Context context) {
  return pw.Align(
    alignment: pw.Alignment.centerRight,
    child: pw.Text(
      'Generated by GIC EFOMIS · Page ${context.pageNumber} of ${context.pagesCount}',
      style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
    ),
  );
}

pw.Widget _sectionTitle(String text) {
  return pw.Padding(
    padding: const pw.EdgeInsets.only(top: 10, bottom: 5),
    child: pw.Text(text,
        style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
  );
}

pw.Widget _labeled(String label, String value) {
  return pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 5),
    child: pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(
          width: 130,
          child: pw.Text('$label:',
              style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
        ),
        pw.Expanded(child: pw.Text(value, style: const pw.TextStyle(fontSize: 9, height: 1.4))),
      ],
    ),
  );
}

List<pw.Widget> _bullets(List<String> items) {
  if (items.isEmpty) {
    return [pw.Text('—', style: const pw.TextStyle(fontSize: 9))];
  }
  return [
    for (final item in items)
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('•  ', style: const pw.TextStyle(fontSize: 9)),
          pw.Expanded(child: pw.Text(item, style: const pw.TextStyle(fontSize: 9, height: 1.4))),
        ],
      ),
  ];
}

pw.Widget _detailsTable(List<List<String>> rows) {
  return pw.TableHelper.fromTextArray(
    headers: const ['Field', 'Value'],
    data: rows,
    border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
    headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
    headerDecoration: const pw.BoxDecoration(color: PdfColors.indigo700),
    cellStyle: const pw.TextStyle(fontSize: 9),
    cellPadding: const pw.EdgeInsets.all(5),
    columnWidths: const {0: pw.FlexColumnWidth(1.1), 1: pw.FlexColumnWidth(2.4)},
  );
}

// Dynamic template sections (new reports) — each section under its own bold
// header. Falls back to an empty list so the caller can render legacy fields.
List<pw.Widget> _templateSections(Map<String, dynamic> data) {
  final raw = data['templateSections'];
  if (raw is! Map || raw.isEmpty) return const [];
  final entries = raw.entries
      .map((e) => MapEntry(e.key.toString(), _str(e.value)))
      .where((e) => e.value.isNotEmpty)
      .toList();
  if (entries.isEmpty) return const [];
  return [
    _sectionTitle('Assessment Findings'),
    for (final e in entries)
      pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 8),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(e.key,
                style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
            pw.SizedBox(height: 2),
            pw.Text(e.value, style: const pw.TextStyle(fontSize: 9, height: 1.4)),
          ],
        ),
      ),
  ];
}

// Legacy pre-template report fields.
List<pw.Widget> _legacySections(Map<String, dynamic> data) {
  final entries = <String, dynamic>{
    'Tasks Performed': data['tasksPerformed'],
    'Outcomes Achieved': data['outcomesAchieved'],
    'Challenges': data['challenges'],
    'Solutions Provided': data['solutionsProvided'],
    'Summary Notes': data['finalReport'],
  }.entries.where((e) => _str(e.value).isNotEmpty).toList();
  if (entries.isEmpty) return const [];
  return [
    _sectionTitle('Assessment Findings'),
    for (final e in entries) _labeled(e.key, _str(e.value)),
  ];
}

pw.Widget _statusBlock(Map<String, dynamic> data) {
  final status = _str(data['status']).isEmpty ? 'Pending Dean Review' : _str(data['status']);
  final items = <String, String>{
    'Status': status,
    if (_str(data['deptHeadFeedback']).isNotEmpty)
      'Dept Head Feedback': _str(data['deptHeadFeedback']),
    if (_str(data['revisionFeedback']).isNotEmpty)
      'Dean Feedback': _str(data['revisionFeedback']),
    if (_str(data['deptHeadReviewedBy']).isNotEmpty)
      'Reviewed By (Dept Head)': _str(data['deptHeadReviewedBy']),
    if (_str(data['reviewedBy']).isNotEmpty)
      'Reviewed By (Dean)': _str(data['reviewedBy']),
  };
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      for (final e in items.entries)
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 4),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(
                width: 150,
                child: pw.Text('${e.key}:',
                    style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
              ),
              pw.Expanded(child: pw.Text(e.value, style: const pw.TextStyle(fontSize: 9))),
            ],
          ),
        ),
    ],
  );
}

pw.Widget _signatureBlock(String title, String caption) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Container(height: 1, color: PdfColors.grey600, width: double.infinity),
      pw.SizedBox(height: 5),
      pw.Text(title, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
      pw.Text(caption, style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
    ],
  );
}

pw.Widget _signOffBlock() {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      _sectionTitle('Sign-off & Approval'),
      pw.Text('Reviewer notes:',
          style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
      pw.Container(
        width: double.infinity,
        height: 46,
        decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey400)),
      ),
      pw.SizedBox(height: 26),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Expanded(child: _signatureBlock('Department Head', 'Name & Signature · Date')),
          pw.SizedBox(width: 28),
          pw.Expanded(child: _signatureBlock('Dean', 'Name & Signature · Date')),
        ],
      ),
    ],
  );
}

// ---------------------------------------------------------------------------
// Public entry points
// ---------------------------------------------------------------------------

/// Render the native print preview for a generated document.
Future<void> _printDocument(pw.Document doc, String name) async {
  await Printing.layoutPdf(
    name: name,
    onLayout: (format) async => doc.save(),
  );
}

/// Print a submitted Enterprise Visit Plan (any status — shows objectives,
/// expected outcomes, resources, approval status and sign-off block).
Future<void> printVisitPlanPdf(Map<String, dynamic> data) async {
  final doc = pw.Document(title: 'Enterprise Visit Plan');
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      header: (context) => _header('Enterprise Visit Plan'),
      footer: _footer,
      build: (context) => [
        _detailsTable([
          ['Document Type', 'Enterprise Visit Plan'],
          ['Date', _fmtDate(data['timestamp'])],
          ['Department', _orDash(data['department'])],
          ['Expert Name', _orDash(data['expertName'] ?? data['submittedBy'])],
          ['Enterprise Name', _orDash(data['targetEnterprise'])],
          ['Location / Woreda', _orDash(data['location'])],
          [
            'Visit Dates',
            '${_orDash(data['startDate'])}  →  ${_orDash(data['endDate'])}',
          ],
          ['Expert Contact', _orDash(data['submittedBy'])],
        ]),
        _sectionTitle('Objectives & Planned Tasks'),
        ..._bullets(_lines(data['tasks'] ?? data['description']?.toString())),
        if (_str(data['expectedOutcomes']).isNotEmpty) ...[
          _sectionTitle('Expected Outcomes'),
          pw.Text(_str(data['expectedOutcomes']), style: const pw.TextStyle(fontSize: 9, height: 1.4)),
        ],
        if (_str(data['resources']).isNotEmpty) ...[
          _sectionTitle('Resources / Tools Required'),
          pw.Text(_str(data['resources']), style: const pw.TextStyle(fontSize: 9, height: 1.4)),
        ],
        _sectionTitle('Approval Status'),
        _statusBlock(data),
        pw.SizedBox(height: 14),
        _signOffBlock(),
      ],
    ),
  );
  await _printDocument(doc, 'GIC_Visit_Plan');
}

/// Print a completed Enterprise Visit Support Report — renders the chosen
/// report template's dynamic sections (or legacy fields), findings,
/// recommendations, approval status and sign-off block.
Future<void> printSupportReportPdf(Map<String, dynamic> data) async {
  final doc = pw.Document(title: 'Enterprise Visit Support Report');
  final templateSections = _templateSections(data);
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      header: (context) => _header('Enterprise Visit Support Report'),
      footer: _footer,
      build: (context) => [
        _detailsTable([
          ['Document Type', 'Enterprise Visit Support Report'],
          [
            'Report Date',
            _fmtDate(data['reportDate'] ?? data['completedAt'] ?? data['timestamp']),
          ],
          ['Department', _orDash(data['department'])],
          ['Expert Name', _orDash(data['expertName'] ?? data['submittedBy'])],
          ['Enterprise Name', _orDash(data['targetEnterprise'])],
          ['Location / Woreda', _orDash(data['location'])],
          ['Sector', _orDash(data['sector'])],
          if (_str(data['reportTemplate']).isNotEmpty)
            ['Report Format', _str(data['reportTemplate'])],
          ['Verified By', _orDash(data['verifiedBy'])],
        ]),
        if (templateSections.isNotEmpty)
          ...templateSections
        else
          ..._legacySections(data),
        if (_str(data['expectedOutcomes']).isNotEmpty) ...[
          _sectionTitle('Expected Outcomes'),
          pw.Text(_str(data['expectedOutcomes']), style: const pw.TextStyle(fontSize: 9, height: 1.4)),
        ],
        _sectionTitle('Approval Status'),
        _statusBlock(data),
        pw.SizedBox(height: 14),
        _signOffBlock(),
      ],
    ),
  );
  await _printDocument(doc, 'GIC_Visit_Report');
}

/// Print Enterprise contact details from the department enterprise directory.
Future<void> printEnterpriseDetailsPdf(Map<String, dynamic> data) async {
  final doc = pw.Document(title: 'Enterprise Details');
  final bool isModel = data['isModel'] == true;
  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      header: (context) => _header('Enterprise Contact Details'),
      footer: _footer,
      build: (context) => [
        _detailsTable([
          ['Enterprise Name', _orDash(data['entName'])],
          ['Industry Sector', _orDash(data['sector'])],
          ['Type', isModel ? 'Model Enterprise' : 'Standard Enterprise'],
          ['Department', _orDash(data['department'])],
          ['Location / Address', _orDash(data['address'] ?? data['woreda'])],
          ['Contact Person', _orDash(data['contactPerson'] ?? data['repName'])],
          ['Position / Role', _orDash(data['position'])],
          ['Phone', _orDash(data['phone'])],
          ['Email', _orDash(data['email'])],
        ]),
        pw.SizedBox(height: 20),
        _signOffBlock(),
      ],
    ),
  );
  await _printDocument(doc, 'GIC_Enterprise_Details');
}
